//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace driveStatsRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip()
        {
            this.tripDatas = new HashSet<tripData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public string tripDate { get; set; }
        public string startLatitude { get; set; }
        public string startLongitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tripData> tripDatas { get; set; }
        public virtual user user { get; set; }
    }
}
